<?php include 'header.php';
session_start();

$title = "Student Term Marks System"; ?>

<body>
  <?php include 'navbar.php'; ?>

  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" style="margin-top: 50px;">
    <h2>Welcome</h2>

    <div class="mb-3 row">

      <div class="card">
        <div class="card-body">
          Student Term Test Marking System facilitates easy management of class students and their term test marks. Marks can be added by subject teachers and students can be added
          by class teacher to his/her class. Term report can be generated at any time with their average and total. Student rank also auto generated by the system based on their performance.

        </div>
      </div>

    </div>
  </main>
  </div>
  </div>
  <?php include 'footer.php'; ?>